spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/poc
    username: jeanfernandes
    password: admin
